# This workflow will install a built Ruby version, install dependencies, and
# deploy app.
name: "Ruby on Rails CD"
on:
  workflow_call:
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.event.repository.name }}
    steps:
      - name: Login to docker.io
        run: docker login -u oauth -p ${{ secrets.YC_TOKEN }} cr.yandex
      
      - name: Get repository code
        uses: actions/checkout@v3

      - name: "Set TAG environmental variable"
        run: |
          echo "TAG=cr.yandex/${{ secrets.REG_ID }}/$REPO_NAME:${GITHUB_REF:11}-${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Build image
        run: docker build -t $TAG -f Dockerfile .

      - name: Tag latest
        run: docker tag $TAG cr.yandex/${{ secrets.REG_ID }}/$REPO_NAME:active
      
      - name: Push image to docker.io
        run: |
          docker push $TAG
          docker push cr.yandex/${{ secrets.REG_ID }}/$REPO_NAME:active
        
      - name: Logout from docker.io
        run: docker logout
  
  deploy:
    needs: [build_and_push]
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.event.repository.name }}
    steps:
      - name: Create directory
        run: mkdir -p ~/.ssh/

      - name: Create secret_key
        run: echo "${{ secrets.BASTYON_PRIV_KEY }}" >> ~/.ssh/id_rsa

      - name: Chmod
        run: chmod 600 ~/.ssh/id_rsa

      - name: Keyscan
        run: ssh-keyscan -H ${{ secrets.BASTYON_ADDR }} > ~/.ssh/known_hosts

      - name: ssh
        run: |
          ssh skachan@${{ secrets.BASTYON_ADDR }} "export YC_TOKEN=${{ secrets.YC_TOKEN }} && export DOCKER_PASSWORD=${{ secrets.YC_TOKEN }} && bash check_state.bash && ansible-playbook -i terraform-inventory ./ansible/$REPO_NAME.yml"
