# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  workflow_call:
jobs:
  test_and_lint:
    runs-on: ubuntu-latest
#    container: 
#      image: 'Dockerfile'
#      env:
#        DATABASE_URL: "postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@${{ secrets.DATABASE_HOST }}:5432/dbposts"
#        DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
#        DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
#        DATABASE_LOGIN: ${{ secrets.DATABASE_LOGIN }}
#        DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
#    services:
#      dbposts:
#        image: postgres:11-alpine
#        ports:
#          - "5432:5432"
#        env:
#          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
#          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create_docker_network
        run: docker network create -d bridge test-bridge-network
      - name: Create_db
        run: docker run -d --name ${{ secrets.DATABASE_HOST }} --network test-bridge-network -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} postgres:11-alpine
      - name: Start_test
        run: docker build -f Dockerfile_test --network test-bridge-network --build-arg DATABASE_HOST=${{ secrets.DATABASE_HOST }} --build-arg DATABASE_NAME=${{ secrets.DATABASE_NAME }} --build-arg DATABASE_LOGIN=${{ secrets.DATABASE_LOGIN }} --build-arg DATABASE_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} -t test .
        
      # Add or replace dependency steps here
#      - name: Install Ruby and gems
#        run: bundle install
#      # Add or replace database setup steps here
#      - name: Set up database schema
#        run: rails db:create
#      # Add or replace test runners here
#      - name: Run tests
#        run: echo "tests have been provided"
#       run: bin/rake
#      # Add or replace any other lints here
#      - name: Lint Ruby files
#        run: echo "lint has been provided"
#       run: bin/rubocop --parallel
